# coding=utf-8
"""Default model config seed data for SQLite initialization."""

SVM_MODELS = {
    "default": {
        "name_en": "default", "name_zh": "default",
        "model_rel_path": "svm/default/svm_model_tuned.pkl",
        "scaler_rel_path": "svm/default/scaler.pkl",
        "training_rel_path": "svm/default/training.csv",
        "default_txt_rel_path": "svm/default/newdata.txt",
    },
    "brca": {
        "name_en": "BRCA_SVM", "name_zh": "BRCA_SVM",
        "model_rel_path": "svm/brca/svm_model_tuned.pkl",
        "scaler_rel_path": "svm/brca/scaler.pkl",
        "training_rel_path": "svm/brca/training.csv",
        "default_txt_rel_path": "svm/brca/newdata.txt",
    },
    "brca_mix": {
        "name_en": "BRCA_MIX_SVM", "name_zh": "BRCA_MIX_SVM",
        "model_rel_path": "svm/brca_mix/svm_model_tuned.pkl",
        "scaler_rel_path": "svm/brca_mix/scaler.pkl",
        "training_rel_path": "svm/brca_mix/training.csv",
        "default_txt_rel_path": "svm/brca_mix/newdata.txt",
    },
    "p": {
        "name_en": "P_SVM", "name_zh": "P_SVM",
        "model_rel_path": "svm/p/svm_model_tuned.pkl",
        "scaler_rel_path": "svm/p/scaler.pkl",
        "training_rel_path": "svm/p/training.csv",
        "default_txt_rel_path": "svm/p/newdata.txt",
    },
    "p_mix": {
        "name_en": "PMIX_SVM", "name_zh": "PMIX_SVM",
        "model_rel_path": "svm/p_mix/svm_model_tuned.pkl",
        "scaler_rel_path": "svm/p_mix/scaler.pkl",
        "training_rel_path": "svm/p_mix/training.csv",
        "default_txt_rel_path": "svm/p_mix/newdata.txt",
    },
    "hpv": {
        "name_en": "HPV_SVM", "name_zh": "HPV_SVM",
        "model_rel_path": "svm/hpv/svm_model_tuned.pkl",
        "scaler_rel_path": "svm/hpv/scaler.pkl",
        "training_rel_path": "svm/hpv/training.csv",
        "default_txt_rel_path": "svm/hpv/newdata.txt",
    },
    "gzb": {
        "name_en": "GZB_SVM", "name_zh": "GZB_SVM",
        "model_rel_path": "svm/gzb/svm_model_tuned.pkl",
        "scaler_rel_path": "svm/gzb/scaler.pkl",
        "training_rel_path": "svm/gzb/training.csv",
        "default_txt_rel_path": "svm/gzb/newdata.txt",
    },
    "han": {
        "name_en": "HAN_SVM", "name_zh": "HAN_SVM",
        "model_rel_path": "svm/han/svm_model_tuned.pkl",
        "scaler_rel_path": "svm/han/scaler.pkl",
        "training_rel_path": "svm/han/training.csv",
        "default_txt_rel_path": "svm/han/newdata.txt",
    },
    "lei": {
        "name_en": "LEI_SVM", "name_zh": "LEI_SVM",
        "model_rel_path": "svm/lei/svm_model_tuned.pkl",
        "scaler_rel_path": "svm/lei/scaler.pkl",
        "training_rel_path": "svm/lei/training.csv",
        "default_txt_rel_path": "svm/lei/newdata.txt",
    },
    "niao": {
        "name_en": "NIAO_SVM", "name_zh": "NIAO_SVM",
        "model_rel_path": "svm/niao/svm_model_tuned.pkl",
        "scaler_rel_path": "svm/niao/scaler.pkl",
        "training_rel_path": "svm/niao/training.csv",
        "default_txt_rel_path": "svm/niao/newdata.txt",
    },
    "shui": {
        "name_en": "SHUI_SVM", "name_zh": "SHUI_SVM",
        "model_rel_path": "svm/shui/svm_model_tuned.pkl",
        "scaler_rel_path": "svm/shui/scaler.pkl",
        "training_rel_path": "svm/shui/training.csv",
        "default_txt_rel_path": "svm/shui/newdata.txt",
    },
    "xueqing": {
        "name_en": "XUEQING_SVM", "name_zh": "XUEQING_SVM",
        "model_rel_path": "svm/xueqing/svm_model_tuned.pkl",
        "scaler_rel_path": "svm/xueqing/scaler.pkl",
        "training_rel_path": "svm/xueqing/training.csv",
        "default_txt_rel_path": "svm/xueqing/newdata.txt",
    },
    "pesticide": {
        "name_en": "PESTICIDE_SVM", "name_zh": "PESTICIDE_SVM",
        "model_rel_path": "svm/pesticide/svm_model_tuned.pkl",
        "scaler_rel_path": "svm/pesticide/scaler.pkl",
        "training_rel_path": "svm/pesticide/training.csv",
        "default_txt_rel_path": "svm/pesticide/newdata.txt",
    },
    "osteoporosis": {
        "name_en": "Osteoporosis_SVM", "name_zh": "Osteoporosis_SVM",
        "model_rel_path": "svm/osteoporosis/svm_model_tuned.pkl",
        "scaler_rel_path": "svm/osteoporosis/scaler.pkl",
        "training_rel_path": "svm/osteoporosis/training.csv",
        "default_txt_rel_path": "svm/osteoporosis/newdata.txt",
    },
    "quino": {
        "name_en": "Quino_SVM", "name_zh": "Quino_SVM",
        "model_rel_path": "svm/quino/svm_model_tuned.pkl",
        "scaler_rel_path": "svm/quino/scaler.pkl",
        "training_rel_path": "svm/quino/training.csv",
        "default_txt_rel_path": "svm/quino/newdata.txt",
    },
    "ciplvfx": {
        "name_en": "CIPLVFX_SVM", "name_zh": "CIPLVFX_SVM",
        "model_rel_path": "svm/ciplvfx/svm_model_tuned.pkl",
        "scaler_rel_path": "svm/ciplvfx/scaler.pkl",
        "training_rel_path": "svm/ciplvfx/training.csv",
        "default_txt_rel_path": "svm/ciplvfx/newdata.txt",
    },
    "cippef": {
        "name_en": "CIPPEF_SVM", "name_zh": "CIPPEF_SVM",
        "model_rel_path": "svm/cippef/svm_model_tuned.pkl",
        "scaler_rel_path": "svm/cippef/scaler.pkl",
        "training_rel_path": "svm/cippef/training.csv",
        "default_txt_rel_path": "svm/cippef/newdata.txt",
    },
    "cippeflvfx": {
        "name_en": "CIPPEFLVFX_SVM", "name_zh": "CIPPEFLVFX_SVM",
        "model_rel_path": "svm/cippeflvfx/svm_model_tuned.pkl",
        "scaler_rel_path": "svm/cippeflvfx/scaler.pkl",
        "training_rel_path": "svm/cippeflvfx/training.csv",
        "default_txt_rel_path": "svm/cippeflvfx/newdata.txt",
    },
    "peflvfx": {
        "name_en": "PEFLVFX_SVM", "name_zh": "PEFLVFX_SVM",
        "model_rel_path": "svm/peflvfx/svm_model_tuned.pkl",
        "scaler_rel_path": "svm/peflvfx/scaler.pkl",
        "training_rel_path": "svm/peflvfx/training.csv",
        "default_txt_rel_path": "svm/peflvfx/newdata.txt",
    },
}

TREE_MODELS = {
    "hu_r": {
        "name_en": "胡萝卜素和视黄醇混合", "name_zh": "胡萝卜素和视黄醇混合",
        "model_rel_path": "tree/HU_R/tree_model.pkl",
        "training_rel_path": "tree/HU_R/HU_R.csv",
        "default_txt_rel_path": "tree/HU_R/new_data_hu_r.txt",
    },
    "hu_vd": {
        "name_en": "胡萝卜素和VD混合", "name_zh": "胡萝卜素和VD混合",
        "model_rel_path": "tree/HUVD/tree_model.pkl",
        "training_rel_path": "tree/HUVD/hu_vd2.csv",
        "default_txt_rel_path": "tree/HUVD/new_data_hu_vd.txt",
    },
    "hu_vd_vk": {
        "name_en": "胡萝卜素和VD、VK混合", "name_zh": "胡萝卜素和VD、VK混合",
        "model_rel_path": "tree/HUVDVK/tree_model.pkl",
        "training_rel_path": "tree/HUVDVK/HU_VD_VK.csv",
        "default_txt_rel_path": "tree/HUVDVK/new_data_HU_VD_VK.txt",
    },
    "hu_vk": {
        "name_en": "胡萝卜素和VK混合", "name_zh": "胡萝卜素和VK混合",
        "model_rel_path": "tree/huvk/tree_model.pkl",
        "training_rel_path": "tree/huvk/hu_vk.csv",
        "default_txt_rel_path": "tree/huvk/new_data_hu_vk.txt",
    },
    "vk_r_vd": {
        "name_en": "视黄醇和VK、VD混合", "name_zh": "视黄醇和VK、VD混合",
        "model_rel_path": "tree/VKRVD/tree_model.pkl",
        "training_rel_path": "tree/VKRVD/VK_R_VD.csv",
        "default_txt_rel_path": "tree/VKRVD/new_data_VK_R_VD.txt",
    },
}

QUANTITATIVE_COMPOUNDS = {
    "retinol": {
        "name_en": "Retinol", "name_zh": "Retinol",
        "unit": "ug/ml",
        "required_rows": 796,
        "intensity_1": {"row": 468, "index": 467, "column": 1},
        "intensity_2": {"row": 796, "index": 795, "column": 1},
        "formula": {"a": 0.0242, "b": 0.8753, "description": "x = (y - 0.8753) / 0.0242"},
    },
    "vitamin_k": {
        "name_en": "Vitamin K", "name_zh": "Vitamin K",
        "unit": "ug/ml",
        "required_rows": 796,
        "intensity_1": {"row": 468, "index": 467, "column": 1},
        "intensity_2": {"row": 796, "index": 795, "column": 1},
        "formula": {"a": 0.0018, "b": 0.4411, "description": "x = (y - 0.4411) / 0.0018"},
    },
    "vitamin_d": {
        "name_en": "Vitamin D", "name_zh": "Vitamin D",
        "unit": "ug/ml",
        "required_rows": 699,
        "intensity_1": {"row": 468, "index": 467, "column": 1},
        "intensity_2": {"row": 699, "index": 698, "column": 1},
        "formula": {"a": 0.0096, "b": 0.0792, "description": "x = (y - 0.0792) / 0.0096"},
    },
    "carotene": {
        "name_en": "Carotene", "name_zh": "Carotene",
        "unit": "ng/ml",
        "required_rows": 796,
        "intensity_1": {"row": 468, "index": 467, "column": 1},
        "intensity_2": {"row": 796, "index": 795, "column": 1},
        "formula": {"a": 0.008, "b": 0.2946, "description": "x = (y - 0.2946) / 0.008"},
    },
    "brca1_mt": {
        "name_en": "BRCA1_MT", "name_zh": "BRCA1_MT",
        "unit": "nM",
        "required_rows": 817,
        "intensity_1": {"row": 135, "index": 134, "column": 1},
        "intensity_2": {"row": 712, "index": 711, "column": 1},
        "formula": {"a": 0.0053, "b": 1.1221, "description": "x = (y - 1.1221) / 0.0053"},
    },
    "brca1_wt": {
        "name_en": "BRCA1_WT", "name_zh": "BRCA1_WT",
        "unit": "nM",
        "required_rows": 817,
        "intensity_1": {"row": 135, "index": 134, "column": 1},
        "intensity_2": {"row": 712, "index": 711, "column": 1},
        "formula": {"a": 0.0054, "b": 0.705, "description": "x = (y - 0.705) / 0.0054"},
    },
    "p16": {
        "name_en": "p16", "name_zh": "p16",
        "unit": "nM",
        "required_rows": 817,
        "intensity_1": {"row": 135, "index": 134, "column": 1},
        "intensity_2": {"row": 712, "index": 711, "column": 1},
        "formula": {"a": 0.0031, "b": 1.345, "description": "x = (y - 1.345) / 0.0031"},
    },
    "p21": {
        "name_en": "p21", "name_zh": "p21",
        "unit": "nM",
        "required_rows": 817,
        "intensity_1": {"row": 135, "index": 134, "column": 1},
        "intensity_2": {"row": 712, "index": 711, "column": 1},
        "formula": {"a": 0.0066, "b": -1.0112, "description": "x = (y + 1.0112) / 0.0066"},
    },
    "p53": {
        "name_en": "p53", "name_zh": "p53",
        "unit": "nM",
        "required_rows": 817,
        "intensity_1": {"row": 135, "index": 134, "column": 1},
        "intensity_2": {"row": 712, "index": 711, "column": 1},
        "formula": {"a": 0.0076, "b": 0.8041, "description": "x = (y - 0.8041) / 0.0076"},
    },
    "crp": {
        "name_en": "C-Reactive Protein", "name_zh": "C-Reactive Protein",
        "unit": "μg/ml",
        "required_rows": 1209,
        "intensity_1": {"row": 343, "index": 342, "column": 1},
        "intensity_2": {"row": 1177, "index": 1176, "column": 1},
        "formula": {"a": 0.035, "b": 0.0162, "description": "x = (y - 0.0162) / 0.035"},
    },
    "il": {
        "name_en": "Interleukin", "name_zh": "Interleukin",
        "unit": "ng/ml",
        "required_rows": 1280,
        "intensity_1": {"row": 346, "index": 345, "column": 1},
        "intensity_2": {"row": 1177, "index": 1176, "column": 1},
        "formula": {"a": 0.0025, "b": 0.1159, "description": "x = (y - 0.1159) / 0.0025"},
    },
    "ua": {
        "name_en": "Uric Acid", "name_zh": "Uric Acid",
        "unit": "μg/ml",
        "required_rows": 1280,
        "intensity_1": {"row": 639, "index": 638, "column": 1},
        "intensity_2": {"row": 1177, "index": 1176, "column": 1},
        "formula": {"a": 0.099, "b": 3.7192, "description": "x = (y - 3.7192) / 0.099"},
    },
    "sjl": {
        "name_en": "Thiabendazole", "name_zh": "Thiabendazole",
        "unit": "ng/ml",
        "required_rows": 850,
        "intensity_1": {"row": 215, "index": 214, "column": 1},
        "intensity_2": {"row": 298, "index": 297, "column": 1},
        "formula": {"a": 0.528, "b": 0.227, "description": "x = (y - 0.227) / 0.528"},
        "transform": "10^x",
    },
    "fms": {
        "name_en": "Thiram", "name_zh": "Thiram",
        "unit": "ng/ml",
        "required_rows": 850,
        "intensity_1": {"row": 579, "index": 578, "column": 1},
        "intensity_2": {"row": 298, "index": 297, "column": 1},
        "formula": {"a": 1.058, "b": -1.295, "description": "x = (y - (-1.295)) / 1.058"},
        "transform": "10^x",
    },
    "cip": {
        "name_en": "CIP", "name_zh": "CIP",
        "unit": "ug/ml",
        "required_rows": 850,
        "intensity_1": {"row": 579, "index": 578, "column": 1},
        "intensity_2": {"row": 301, "index": 300, "column": 1},
        "formula": {"a": 0.9835, "b": 0.6464, "description": "x = (y - 0.6464) / 0.9835"},
    },
    "norf": {
        "name_en": "NORF", "name_zh": "NORF",
        "unit": "ug/ml",
        "required_rows": 850,
        "intensity_1": {"row": 402, "index": 401, "column": 1},
        "intensity_2": {"row": 798, "index": 797, "column": 1},
        "formula": {"a": 0.991, "b": 1.8743, "description": "x = (y - 1.8743) / 0.991"},
    },
    "pef": {
        "name_en": "PEF", "name_zh": "PEF",
        "unit": "ug/ml",
        "required_rows": 850,
        "intensity_1": {"row": 404, "index": 403, "column": 1},
        "intensity_2": {"row": 795, "index": 794, "column": 1},
        "formula": {"a": 0.0451, "b": 0.7205, "description": "x = (y - 0.7205) / 0.0451"},
    },
    "cip_rengonghu": {
        "name_en": "CIP", "name_zh": "CIP",
        "unit": "umol/ml",
        "required_rows": 850,
        "intensity_1": {"row": 588, "index": 587, "column": 1},
        "intensity_2": {"row": 1122, "index": 1121, "column": 1},
        "formula": {"a": 0.9934, "b": 10.509, "description": "x = (y - 10.509) / 0.9934"},
    },
}


